### ISSUE TITLE
`.lock()` allocates memory on first execution on Linux because of `sys_info`

### ISSUE THREAD

**Issue by GoldsteinE** [garypen/mintex#1]
`LOOP_LIMIT` is lazily calculated in first call to `.lock()`. On Linux, this calculation involves allocating a `String` and opening a file. This could cause deadlocks and other unfortunate consequences in some settings, e.g. allocators.

https://github.com/FillZpp/sys-info-rs/blob/60ecf1470a5b7c90242f429934a3bacb6023ec4d/lib.rs#L570-L587

The resulting value of `sys_info::cpu_speed()` is not that useful (at least on Linux) anyway, since it’s only related to the first core found in `/proc/cpuinfo` and it’s unknown whether this is _current_ or _max_ CPU clock speed.

I propose just hardcoding `LOOP_LIMIT` to some sensible value.

**Comment by garypen** [comment]
Yep, you are right. I did have LOOP_LIMIT hard-coded [at one point ](https://github.com/garypen/mintex/commit/ce8eeac8ac87f052aa0d2a591c767a068cba3ed4)but got too clever.

I'll revert that change and make a release soon.
